### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by midzer** [Astropilot/Bomberman#2]
Hi again ;D

Is it possible to port the game to an offline mode?

So you could play on the same machine with multiple players via keyboard?

Enjoy your time
midzer

**Comment by Astropilot** [comment]
Hi again :D

Sadly this was just a school project made 4 years ago, it was not really intended to be really used outside of it and to evolute. I just made the code available for learning purposes.
And as the networking was at the core of the game, making it offline would require a lot of changes and I do not have neither the motivation nor the time :(

Kind regards,
Astropilot

**Comment by midzer** [comment]
Thanks for your answer and no worries :)

Meanwhile I've found https://github.com/bjaraujo/Bombermaaan which has offline mode already implemented.

Cya
midzer
